
CREATE TABLE IF NOT EXISTS PUBLIC.CATEGORY (
	CATEGORY_ID INTEGER auto_increment,
	NAME VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (CATEGORY_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_3 ON PUBLIC.CATEGORY (CATEGORY_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UK_46CCWNSI9409T36LURVTYLJAK_INDEX_3 ON PUBLIC.CATEGORY (NAME);


CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCT (
	PRODUCT_ID INTEGER auto_increment,
	DESCRIPTION VARCHAR(255),
	MANUFACTURER VARCHAR(255),
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	SERIAL_NUM VARCHAR(255),
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY (PRODUCT_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_1 ON PUBLIC.PRODUCT (PRODUCT_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UK_383I0AWXQLQ7PC33HIL7AFBGO_INDEX_1 ON PUBLIC.PRODUCT (PRODUCT_NAME);

CREATE TABLE IF NOT EXISTS PUBLIC.CATEGORY_PRODUCT (
	CATEGORY_ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	CONSTRAINT FKFR6RJC04HTBTC3XAS2B9XMQ7R FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORY(CATEGORY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKSSROQJ2VYIAUJFLEKLQ1IFIGJ FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(PRODUCT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS FKFR6RJC04HTBTC3XAS2B9XMQ7R_INDEX_C ON PUBLIC.CATEGORY_PRODUCT (CATEGORY_ID);
CREATE INDEX IF NOT EXISTS FKSSROQJ2VYIAUJFLEKLQ1IFIGJ_INDEX_C ON PUBLIC.CATEGORY_PRODUCT (PRODUCT_ID);
