package com.respect.learn.catalogservice.jdbcrepo;

public interface Queries {

	String FINDPRODUCT = "SELECT A.*, C.* from PRODUCT A " + "LEFT OUTER JOIN CATEGORY_PRODUCT B on A.PRODUCT_ID=B.PRODUCT_ID "
			+ "LEFT OUTER JOIN CATEGORY C ON B.CATEGORY_ID=C.CATEGORY_ID " + "WHERE A.PRODUCT_NAME + :name";

	String FINDALLPRODUCT = "SELECT A.*, C.* from PRODUCT A " + "LEFT OUTER JOIN CATEGORY_PRODUCT B on A.PRODUCT_ID=B.PRODUCT_ID "
			+ "LEFT OUTER JOIN CATEGORY C ON B.CATEGORY_ID=C.CATEGORY_ID ";

	String INSERTCATEGORY = "INSERT IGNORE INTO CATEGORY(NAME) VALUES (:name)";

	String INSERTPRODUCT = "INSERT IGNORE INTO PRODUCT(DESCRIPTION,MANUFACTURER,PRODUCT_NAME,SERIAL_NUM) VALUES (:DESCRIPTION,:MANUFACTURER,:PRODUCT_NAME,:SERIAL_NUM)";

	String INSERTPRODUCTCATEGORY = "INSERT IGNORE INTO CATEGORY_PRODUCT(PRODUCT_ID, CATEGORY_ID) VALUES (:PRODUCT_ID, :CATEGORY_ID)";

	String UPDATEPRODUCT = "UPDATE PRODUCT SET DESCRIPTION=:DESCRIPTION,MANUFACTURER=:MANUFACTURER,PRODUCT_NAME=:PRODUCT_NAME,SERIAL_NUM=:SERIAL_NUM";

	String DELETEPRODUCT = "DELETE FROM PRODUCT WHERE PRODUCT_ID=:id";

	String DELETEPRODUCTCATEGORY = "DELETE FROM CATEGORY_PRODUCT where PRODUCT_ID=:id";
	
	String DELETEPRODUCTCATEGORY_1 = "DELETE FROM CATEGORY_PRODUCT where CATEGORY_ID=:id";

	String FINDCATEOGY = "SELECT A.*, C.* from PRODUCT A " + "LEFT OUTER JOIN CATEGORY_PRODUCT B on A.PRODUCT_ID=B.PRODUCT_ID "
			+ "LEFT OUTER JOIN CATEGORY C ON B.CATEGORY_ID=C.CATEGORY_ID " + "WHERE C.NAME=:name";

	String FINDALLCATEGORY = FINDALLPRODUCT;

	String UPDATECATEGORY = "UPDATE CATEGORY SET NAME=:name";

	String DELETECATEGORY = "DELETE FROM CATEGORY where CATEGORY_ID=:id";;

}
